### ISSUE TITLE
关于授权使用部分代码的请求

### ISSUE THREAD

**Issue by alexinea** [LonghronShen/SendCloudSDK#1]
你好，List 大大。

我在我的 [SMS](https://github.com/OpenCosmosLoops/SMS) 项目中使用了一部分 SendCloudSDK 的代码（包括部分 [core/SendCloud.cs](https://github.com/LonghronShen/SendCloudSDK/blob/netstandard2.0/src/SendCloudSDK/Core/SendCloud.cs) 和单元测试的代码），由于您没有标记项目授权类型，而我的项目则是 MIT 授权，所以在此想获得您的授权，允许我使用包含上述所列的本项目的部分代码于我的 [SMS](https://github.com/OpenCosmosLoops/SMS) 项目中，谢谢哈：）

**Comment by LonghronShen** [comment]
Hi, I have done the operation to use the MIT license.
Feel free to use it~

**Comment by LonghronShen** [comment]
By the way, I also have Aliyun(Dysms), RongCloud(融云), RongIo(容联云通讯) support. I can send them to you.

**Comment by alexinea** [comment]
目前 AliyunDysms 已经完成了，[融云](https://github.com/OpenCosmosLoops/SMS/tree/master/src/Cosmos.Business.Extensions.SMS.RongCloud)和[容联云通讯](https://github.com/OpenCosmosLoops/SMS/tree/master/src/Cosmos.Business.Extensions.SMS.Yuntongxun)还没开工，欢迎 List 大大一同来完成：）

另外，之后会按照[核心库的接口](https://github.com/OpenCosmosLoops/SMS/tree/master/src/Cosmos.Business.Extensions.SMS/Core/SmsImplements)的设计进行重构，以便打通从SmsSendingServiceProvider到最终SMS实现的整条链路。

**Comment by alexinea** [comment]
融云与容联云通讯实现，接下去将对各实现进行抽象，执行一次重构。
